In [ ]:
import io
import pandas as pd
df = pd.read_csv(io.StringIO('''
Vehicle Type,Performance,Driveability,Luxury,Safety,Fuel,Power,Cargo,Dependability
Compact Car,0.2,0.45,0.35,0.5,0.75,0.1,0.4,0.75
Compact Sport Utility,0.3,0.4,0.1,0.3,0.1,0.4,0.35,0.6
Compact Van,0.1,0.45,0.15,0.1,0.5,0.35,0.85,0.5
Coupe,0.7,0.65,0.25,0.25,0.35,0.3,0.2,0.35
Coupe 2+2,0.65,0.55,0.35,0.3,0.4,0.35,0.25,0.35
Coupe Utility,0.45,0.4,0.2,0.1,0.15,0.75,0.75,0.65
Crossover,0.3,0.25,0.5,0.7,0.5,0.3,0.65,0.5
Fastback,0.7,0.65,0.35,0.15,0.25,0.4,0.3,0.4
Full Sized Sedan,0.3,0.25,0.65,0.7,0.55,0.6,0.65,0.4
Hatchback,0.3,0.6,0.4,0.5,0.65,0.2,0.5,0.7
Landaulet,0.2,0.15,0.9,0.5,0.05,0.3,0.7,0.35
Limousine,0.15,0.15,0.8,0.5,0.05,0.3,0.75,0.4
Luxury Sedan,0.55,0.5,0.9,0.75,0.35,0.6,0.68,0.7
Microcar,0.05,0.5,0.125,0.1,0.9,0.05,0.1,0.65
Microvan,0.1,0.5,0.2,0.1,0.55,0.3,0.85,0.5
Minivan,0.1,0.25,0.55,0.85,0.55,0.15,0.8,0.45
Phaeton,0.1,0.3,0.1,0.5,0.45,0.05,0.2,0.5
Pickup Truck,0.4,0.15,0.15,0.05,0.05,0.9,0.95,0.8
Roadster,0.7,0.9,0.05,0.1,0.25,0.25,0.2,0.3
Roadster 2+2,0.65,0.85,0.15,0.15,0.3,0.3,0.25,0.35
Sedan,0.4,0.4,0.45,0.65,0.65,0.45,0.5,0.45
Shooting Brake,0.2,0.15,0.5,0.7,0.35,0.3,0.75,0.5
Sports,0.9,0.85,0.1,0.1,0.05,0.8,0.1,0.35
Station Wagon,0.25,0.15,0.55,0.75,0.6,0.3,0.75,0.5
Subcompact,0.1,0.4,0.35,0.7,0.9,0.1,0.3,0.8
Supercar,1,1,0.01,0.01,0.01,1,0.01,0.05
Sport Utility Vehicle,0.25,0.15,0.5,0.75,0.25,0.8,0.6,0.4
Touring,0.5,0.75,0.5,0.3,0.4,0.5,0.4,0.4
Town Car,0.15,0.15,0.8,0.5,0.15,0.4,0.6,0.4
Van,0.05,0.1,0.05,0.05,0.05,0.7,0.95,0.7
'''), header=0)

In [ ]:
demographics_gender = {
    "Male": {"Performance": 0.05, "Power": 0.05, "Driveability": 0.05, "Fuel": -0.05, "Safety": -0.05, "Cargo": -0.05},
    "Female": {"Performance": -0.05, "Power": -0.05, "Driveability": -0.05, "Fuel": 0.05, "Safety": 0.05, "Cargo": 0.05},
    "Neutral": {}
}

In [ ]:
demographics_age = {
    "Less Than 25": {"Performance": 0.05, "Fuel": 0.05, "Safety": -0.05, "Luxury": -0.05, "Dependability": 0.05},
    "25-35": {"Performance": -0.05, "Power": -0.05, "Driveability": -0.05, "Safety": 0.05, "Cargo": 0.05, "Dependability": 0.05},
    "35-55": {"Performance": 0.05, "Power": 0.05, "Fuel": -0.05, "Safety": -0.05, "Cargo": -0.05, "Luxury": 0.05, "Dependability": -0.05},
    "Greater Than 55": {"Performance": -0.05, "Power": -0.05, "Fuel": -0.05, "Safety": 0.05, "Luxury": 0.05, "Dependability": 0.05, "Driveability": -0.05}
}

In [ ]:
Check_list = list(demographics_age['Less Than 25'].keys())+\
list(demographics_age['25-35'].keys())+\
list(demographics_age['35-55'].keys())+\
list(demographics_age['Greater Than 55'].keys())+\
list(demographics_gender['Female'].keys())+\
list(demographics_gender['Male'].keys())

for i in Check_list:
  if i not in list(df.columns):
    print(i)

In [ ]:
df.head()

,Vehicle Type,Performance,Driveability,Luxury,Safety,Fuel,Power,Cargo,Dependability
0,Compact Car,0.20,0.45,0.35,0.50,0.75,0.10,0.40,0.75
1,Compact Sport Utility,0.30,0.40,0.10,0.30,0.10,0.40,0.35,0.60
2,Compact Van,0.10,0.45,0.15,0.10,0.50,0.35,0.85,0.50
3,Coupe,0.70,0.65,0.25,0.25,0.35,0.30,0.20,0.35
4,Coupe 2+2,0.65,0.55,0.35,0.30,0.40,0.35,0.25,0.35

In [ ]:
results = []
for i in range(len(df)):
    # Calculate scores for all possible demographic combinations
    best_score = float('-inf')
    best_demographics = None
    for gender in ['Male', 'Female', 'Neutral']:
        for age in ['Less Than 25','25-35','35-55','Greater Than 55']:
            # Calculate score for this demographic combination
            score = 0
            for col in df.columns:
              if col != 'Vehicle Type':
                score += df.iloc[i][col]*(1+demographics_gender[gender].get(col,0)+demographics_age[age].get(col,0))

            # Update best score and demographics if necessary
            if score > best_score:
                best_score = score
                best_demographics = {'gender': gender, 'age': age}

    # Store results for this vehicle type
    results.append({'Vehicle Type': df.iloc[i]['Vehicle Type'], 'Best Demographics Gender': best_demographics['gender'], 'Best Demographics Age': best_demographics['age'], 'Best Score': best_score})

# Create a DataFrame from the results
result_df = pd.DataFrame(results)

In [ ]:
result_df

,Vehicle Type,Best Demographics Gender,Best Demographics Age,Best Score
0,Compact Car,Female,25-35,3.59000
1,Compact Sport Utility,Male,Less Than 25,2.59750
2,Compact Van,Female,Less Than 25,3.07000
3,Coupe,Male,Less Than 25,3.13750
4,Coupe 2+2,Male,Less Than 25,3.26750
5,Coupe Utility,Male,Less Than 25,3.52750
6,Crossover,Female,25-35,3.80000
7,Fastback,Male,Less Than 25,3.29500
8,Full Sized Sedan,Female,25-35,4.16750
9,Hatchback,Female,Less Than 25,3.91500
10,Landaulet,Female,Greater Than 55,3.23250
11,Limousine,Female,25-35,3.18750
12,Luxury Sedan,Female,25-35,5.06050
13,Microcar,Female,Less Than 25,2.56875
14,Microvan,Female,Less Than 25,3.17250
15,Minivan,Female,25-35,3.86500
16,Phaeton,Female,25-35,2.27250
17,Pickup Truck,Male,Less Than 25,3.52250
18,Roadster,Male,Less Than 25,2.87000
19,Roadster 2+2,Male,Less Than 25,3.10500
20,Sedan,Female,Less Than 25,3.99750
21,Shooting Brake,Female,25-35,3.57250
22,Sports,Male,35-55,3.42500
23,Station Wagon,Female,25-35,3.98500
24,Subcompact,Female,25-35,3.77500
25,Supercar,Male,35-55,3.33500
26,Sport Utility Vehicle,Female,25-35,3.74750
27,Touring,Male,Less Than 25,3.80750
28,Town Car,Female,Greater Than 55,3.22000
29,Van,Female,25-35,2.70250

In [91]:
year = 1935
AdjustedYear = year - 1899

Bore_mm = 81.82
Stroke_mm = 68.18
Marq_DesignEngineSkill = 100
Slider_Performance_Torque = 80/100
Slider_Performance_FuelEconomy = 50/100
Slider_DesignFocus_FuelEconomy = 50/100
Slider_DesignFocus_Performance = 50/100
Slider_Technology_Components = 50/100
Slider_Technology_Materials = 50/100
Slider_Technology_Technologies = 50/100
Slider_Technology_Techniques = 50/100
Slider_Layout_Weight = 50/100
Slider_Performance_Revolutions = 50/100

ex_1d01p_year99 = 1.01**(year-1899)
ex_1d005p_year99 = 1.005**(year-1900)
ex_1d004p_year99 = 1.004**(year-1900)
ex_1d0024p_year99 = 1.0024**(year-1900)
ex_1d0105p_year99 = 1.0105**(year-1900)
ex_0d996p_year50R = 0.996**(2050-year)


SubComponent_Layout_Length = 0.85
SubComponent_Layout_Width = 0.9
SubComponent_Layout_PowerRatings = 0.75
SubComponent_Cylinders_PowerRating = 0.75
SubComponent_Cylinders_CylinderCount = 6
SubComponent_Induction_PowerRating = 1.3
SubComponent_Valve_PowerRating = 1
SubComponent_Valve_RPM = 1.08
SubComponent_FuelType_RPM = 1.2
SubComponent_FuelType_PowerRating = 	0.6

In [92]:
Displacement_CC = (0.7854 * ((Bore_mm/10) * (Bore_mm/10)) * (Stroke_mm/10) * SubComponent_Cylinders_CylinderCount)

In [93]:
Torque = 10 + (Marq_DesignEngineSkill/20.0) + \
    ((((25) * ((Slider_Performance_Torque - 0.4)*1.5)*ex_1d01p_year99) + \
    ((4*(SubComponent_Layout_Length + SubComponent_Layout_Width) )*ex_1d005p_year99) - \
    (14 * (Slider_Performance_FuelEconomy+Slider_DesignFocus_FuelEconomy) * ex_1d004p_year99) +\
    (SubComponent_Layout_PowerRatings*5 + SubComponent_Cylinders_PowerRating*13 +\
    SubComponent_FuelType_PowerRating*24 + 100*SubComponent_Induction_PowerRating +\
    (5 * ex_1d004p_year99 * Slider_DesignFocus_Performance) +\
    8*(Slider_Technology_Components+Slider_Technology_Materials + \
    Slider_Technology_Technologies +Slider_Technology_Techniques))*ex_1d0024p_year99))

Torque = Torque * ((SubComponent_Cylinders_CylinderCount * Stroke_mm*0.93 * Bore_mm*0.9)*0.000027)+5

if year < 2050:
    Torque = Torque * ex_0d996p_year50R

Torque = Torque * SubComponent_Valve_PowerRating

In [72]:
tmpAY = AdjustedYear

if tmpAY > 80:
    tmpAY = 80 + ((AdjustedYear-80)/5)


rpm = ((((tmpAY^4)*0.00000420875) - \
    ((19*(tmpAY^3))*0.00016835) + ((427*(tmpAY^2))*0.00126) +\
    ((1315*(tmpAY))*0.01515) + 620 ) + (265 * ex_1d01p_year99 * Slider_DesignFocus_Performance) +\
    (465 * ex_1d0105p_year99 * (Slider_Performance_Revolutions*5.5)) -\
    (10 * ex_1d01p_year99 * SubComponent_Induction_PowerRating) +\
    (55 * ex_1d005p_year99 * (1-Slider_Layout_Weight)) - (30* ex_1d005p_year99 *\
    (Slider_DesignFocus_FuelEconomy + Slider_Performance_FuelEconomy))+  \
    (25 * ex_1d01p_year99 * Slider_Technology_Components) + \
    (25 * ex_1d01p_year99 * Slider_Technology_Materials) + \
    (25 * ex_1d01p_year99 * Slider_Technology_Technologies)) * SubComponent_FuelType_RPM


rpm = rpm * SubComponent_Valve_RPM

rpm = rpm - ((rpm/1.5) * (Stroke_mm/221.136364))

if rpm < 25:
    rpm = 25

In [73]:
hp = (Torque * rpm) / 5252

In [74]:
print(rpm,Torque,hp)

3308.4310783443025 104.87095304346997 66.0621325713256

In [79]:
def cal_optimal_performance(Bore_mm,Stroke_mm):
  Displacement_CC = (0.7854 * ((Bore_mm/10) * (Bore_mm/10)) * (Stroke_mm/10) * SubComponent_Cylinders_CylinderCount)
  Torque = 10 + (Marq_DesignEngineSkill/20.0) + \
    ((((25) * ((Slider_Performance_Torque - 0.4)*1.5)*ex_1d01p_year99) + \
    ((4*(SubComponent_Layout_Length + SubComponent_Layout_Width) )*ex_1d005p_year99) - \
    (14 * (Slider_Performance_FuelEconomy+Slider_DesignFocus_FuelEconomy) * ex_1d004p_year99) +\
    (SubComponent_Layout_PowerRatings*5 + SubComponent_Cylinders_PowerRating*13 +\
    SubComponent_FuelType_PowerRating*24 + 100*SubComponent_Induction_PowerRating +\
    (5 * ex_1d004p_year99 * Slider_DesignFocus_Performance) +\
    8*(Slider_Technology_Components+Slider_Technology_Materials + \
    Slider_Technology_Technologies +Slider_Technology_Techniques))*ex_1d0024p_year99))

  Torque = Torque * ((SubComponent_Cylinders_CylinderCount * Stroke_mm*0.93 * Bore_mm*0.9)*0.000027)+5

  if year < 2050:
      Torque = Torque * ex_0d996p_year50R

  Torque = Torque * SubComponent_Valve_PowerRating
  tmpAY = AdjustedYear

  if tmpAY > 80:
      tmpAY = 80 + ((AdjustedYear-80)/5)


  rpm = ((((tmpAY^4)*0.00000420875) - \
      ((19*(tmpAY^3))*0.00016835) + ((427*(tmpAY^2))*0.00126) +\
      ((1315*(tmpAY))*0.01515) + 620 ) + (265 * ex_1d01p_year99 * Slider_DesignFocus_Performance) +\
      (465 * ex_1d0105p_year99 * (Slider_Performance_Revolutions*5.5)) -\
      (10 * ex_1d01p_year99 * SubComponent_Induction_PowerRating) +\
      (55 * ex_1d005p_year99 * (1-Slider_Layout_Weight)) - (30* ex_1d005p_year99 *\
      (Slider_DesignFocus_FuelEconomy + Slider_Performance_FuelEconomy))+  \
      (25 * ex_1d01p_year99 * Slider_Technology_Components) + \
      (25 * ex_1d01p_year99 * Slider_Technology_Materials) + \
      (25 * ex_1d01p_year99 * Slider_Technology_Technologies)) * SubComponent_FuelType_RPM


  rpm = rpm * SubComponent_Valve_RPM

  rpm = rpm - ((rpm/1.5) * (Stroke_mm/221.136364))

  if rpm < 25:
      rpm = 25
  hp = (Torque * rpm) / 5252
  return hp

In [94]:
bore = 50.00
stroke = 150-bore
max_hp = 0
best_bore = 0
best_stroke = 0
while bore <= 100:
  hp = cal_optimal_performance(bore,stroke)
  if hp > max_hp:
    best_bore = bore
    best_stroke = stroke
    max_hp = hp
  bore += 0.01
  stroke = 150-bore

In [95]:
print(best_bore,best_stroke,max_hp)

85.62000000000828 64.37999999999172 73.03192642539908